import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <iframe src="/vocdoni-widget?electionId=169253a862cb05abb3bf74276ce95f90c4e13c30ceb5e4731beba683f6eb18de&handlers=facebook,github" style={{ display: "block", margin: "0 auto", border:'1px solid red', width: '600px', height: '400px' }}></iframe>
        </div>
      </main>
    </>
  )
}
