import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <iframe src="/vocdoni-widget?electionId=84fc9db5b752e15b00567446ada48f31e9db03ab128ae592269381e200a2065a&handlers=facebook,github" style={{ display: "block", margin: "0 auto", border:'1px solid red', width: '600px', height: '400px' }}></iframe>
        </div>
      </main>
    </>
  )
}
